### ISSUE TITLE
Workshop recipes not displaying correctly.

### ISSUE THREAD

**Issue by Droog71** [logalog42/minegistics#32]
In the latest version, with the new terrain generation, workshop recipes are not displaying correctly.

Current version:
![screenshot_20230317_083407](https://user-images.githubusercontent.com/6352433/225907535-d87c687d-58f9-49f5-b502-8647c49f8d96.png)

Previously:
![screenshot_20230317_082836](https://user-images.githubusercontent.com/6352433/225907445-996568e8-f493-475c-b46c-93aa29220e5d.png)

**Comment by Droog71** [comment]
Cool, great work! I was just going to mention that.
The problem is slightly different with the market:
![screenshot_20230318_075556](https://user-images.githubusercontent.com/6352433/226106000-b7f998f5-6231-4d5f-8f61-60c37bdf690c.png)
I really like the new world generation btw. Nice job.

**Comment by logalog42** [comment]
Changed the entire formspec of the buildings so that should help with things. Still more work to do on them but their better.
