### ISSUE TITLE
Warehouse usage

### ISSUE THREAD

**Issue by ik160** [logalog42/minegistics#34]
Hi, I really enjoy this MOD.
I have one question about "Warehouse".
How can I connect this building to another?
When I connected a warehouse to collector, it stored items.
Then I connected it to factory, but nothing occured.

**Comment by logalog42** [comment]
I'm working on overhauling the formspec so things are kind of a mess right now.

**Comment by ik160** [comment]
Thanks!
________________________________
差出人: logalog42 ***@***.***>
送信日時: Thursday, April 27, 2023 6:02:23 AM
宛先: logalog42/minegistics ***@***.***>
CC: ik160 ***@***.***>; Author ***@***.***>
件名: Re: [logalog42/minegistics] Warehouse usage (Issue #34)


I'm working on overhauling the formspec so things are kind of a mess right now.
